language: rust
sudo: false
language: rust

rust:
- stable
- beta
- nightly

cache:
  directories:
    - $HOME/.cargo
    - target

install:
  - true

env:
  - TRAVIS_CARGO_NIGHTLY_FEATURE=""

script:
- cargo build -- $EXTRA
- cargo test  -- $EXTRA
- cargo doc

matrix:
    allow_failures:
        - rust: nightly
        - rust: beta
