[package]
authors = ["Ceri Storey <cez@necrofish.org.uk>"]
name = "weft"
version = "0.1.0"
repository = "https://github.com/cstorey/weft"
readme = "README.md"
categories = ["web-programming", "template-engine"]

[dependencies]
html5ever = "0.22.3"
markup5ever = "0.7.3"

[dependencies.weft_derive]
path = "../derive"

[dev-dependencies]
regex = "1.0.5"
