version: 2
jobs:
  build:
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: circleci/rust:1.30.1
    steps:
      - checkout # check out the code in the project directory
      - run: cargo test