# Borrowed from https://github.com/sfackler/rust-postgres/blob/04bd98e7edb238511661b311c725a176012bca6a/.circleci/config.yml
# Used under MIT license.

restore_registry: &RESTORE_REGISTRY
  restore_cache:
    key: registry
save_registry: &SAVE_REGISTRY
  save_cache:
    key: registry-{{ .BuildNum }}
    paths:
    - /usr/local/cargo/registry/index
deps_key: &DEPS_KEY
  key: deps-{{ checksum "~/rust-version" }}-{{ checksum "Cargo.lock" }}
restore_deps: &RESTORE_DEPS
  restore_cache:
    <<: *DEPS_KEY
save_deps: &SAVE_DEPS
  save_cache:
    <<: *DEPS_KEY
    paths:
    - target
    - /usr/local/cargo/registry/cache

version: 2
jobs:
  build:
    docker:
      - image: cimg/rust:1.65
        environment:
          RUSTFLAGS: -D warnings
    steps:
      - checkout
      - run: |
          upstream=${CIRCLE_REPOSITORY_URL:-$(git remote  get-url origin)}
          git config --global user.email "circleci@invalid.example"
          git config --global user.name "CircleCI build for ${upstream}"
          git merge --no-edit --no-ff origin/main
      - run: |
          set -euxo pipefail
          echo >> "$BASH_ENV" 'export PATH=${HOME}/bin:$PATH'
      - run: .circleci/shellcheck-install.sh "${HOME}/bin"
      - run: .circleci/shellcheck-run.sh
      - *RESTORE_REGISTRY
      - run: cargo generate-lockfile
      - *SAVE_REGISTRY
      - run: rustc --version | tee ~/rust-version
      - *RESTORE_DEPS
      - run: cargo test --all
      - *SAVE_DEPS
      - run: .circleci/mdbook-install.sh "${HOME}/bin"
      - run: mdbook build docs
      - store_artifacts:
          path: docs/book
      - run: .circleci/git-set-id.sh
      - add_ssh_keys:
          fingerprints:
            - "8c:f0:86:38:cf:6e:a0:23:c4:f5:85:12:ae:b6:f3:4b"
      - run: |
          if [[ "$CIRCLE_BRANCH" = "master" ]]; then
            .circleci/push-to-gh-pages.sh docs/book
          else
            echo 1>&2 "Not deploying docs as not on master; now on $CIRCLE_BRANCH"
          fi
